target 'Lifekeyrn' do
    platform :ios, '9.0'
    use_frameworks!
    inhibit_all_warnings!

    pod 'Firebase/Auth'
    pod 'Firebase/Analytics'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/DynamicLinks'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Storage'
    pod 'Fabric'
    pod 'Crashlytics'

end


